apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  namespace: default
  name: intern
rules:
- apiGroups: ["*"]
  resources: ["pods","pods/log","pods/portforward","services","deployments","configmaps","cronjobs"]
  verbs: ["get","list","watch","describe"]
- apiGroups: ['*']
  resources: ["pods/portforward"]
  verbs: ["create"]