apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: junior
  namespace: stg-mediaad
subjects: 
- kind: ServiceAccount
  name: mehdi-fallahi-o2hw-a
roleRef:
  kind: ClusterRole 
  name: junior
  apiGroup: rbac.authorization.k8s.io