apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: senior
  namespace: stg-mediaad
subjects: 
- kind: ServiceAccount
  name: mehdi-fallahi-o2hw
roleRef:
  kind: ClusterRole 
  name: senior
  apiGroup: rbac.authorization.k8s.io